package org.nmiljkovic.models;
// Generated Aug 13, 2017 2:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airport generated by hbm2java
 */
public class Airport  implements java.io.Serializable {


     private String id;
     private String name;
     private int runwayCount;
     private String city;
     private String country;
     private Set flightsForAirport = new HashSet(0);
     private Set flightsForDestAirport = new HashSet(0);
     private Set gates = new HashSet(0);

    public Airport() {
    }

	
    public Airport(String id, String name, int runwayCount, String city, String country) {
        this.id = id;
        this.name = name;
        this.runwayCount = runwayCount;
        this.city = city;
        this.country = country;
    }
    public Airport(String id, String name, int runwayCount, String city, String country, Set flightsForAirport, Set flightsForDestAirport, Set gates) {
       this.id = id;
       this.name = name;
       this.runwayCount = runwayCount;
       this.city = city;
       this.country = country;
       this.flightsForAirport = flightsForAirport;
       this.flightsForDestAirport = flightsForDestAirport;
       this.gates = gates;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getRunwayCount() {
        return this.runwayCount;
    }
    
    public void setRunwayCount(int runwayCount) {
        this.runwayCount = runwayCount;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set getFlightsForAirport() {
        return this.flightsForAirport;
    }
    
    public void setFlightsForAirport(Set flightsForAirport) {
        this.flightsForAirport = flightsForAirport;
    }
    public Set getFlightsForDestAirport() {
        return this.flightsForDestAirport;
    }
    
    public void setFlightsForDestAirport(Set flightsForDestAirport) {
        this.flightsForDestAirport = flightsForDestAirport;
    }
    public Set getGates() {
        return this.gates;
    }
    
    public void setGates(Set gates) {
        this.gates = gates;
    }




}


