package org.nmiljkovic.models;
// Generated Aug 23, 2017 10:48:40 PM by Hibernate Tools 4.3.1



/**
 * Crew generated by hbm2java
 */
public class Crew  implements java.io.Serializable {


     private CrewId id;
     private Flight flight;
     private User user;

    public Crew() {
    }

    public Crew(CrewId id, Flight flight, User user) {
       this.id = id;
       this.flight = flight;
       this.user = user;
    }
   
    public CrewId getId() {
        return this.id;
    }
    
    public void setId(CrewId id) {
        this.id = id;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


