package org.nmiljkovic.models;
// Generated Aug 27, 2017 8:06:21 PM by Hibernate Tools 4.3.1



/**
 * CrewId generated by hbm2java
 */
public class CrewId  implements java.io.Serializable {


     private int user;
     private int flight;

    public CrewId() {
    }

    public CrewId(int user, int flight) {
       this.user = user;
       this.flight = flight;
    }
   
    public int getUser() {
        return this.user;
    }
    
    public void setUser(int user) {
        this.user = user;
    }
    public int getFlight() {
        return this.flight;
    }
    
    public void setFlight(int flight) {
        this.flight = flight;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CrewId) ) return false;
		 CrewId castOther = ( CrewId ) other; 
         
		 return (this.getUser()==castOther.getUser())
 && (this.getFlight()==castOther.getFlight());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUser();
         result = 37 * result + this.getFlight();
         return result;
   }   


}


