package org.nmiljkovic.models;
// Generated Aug 25, 2017 1:49:43 PM by Hibernate Tools 4.3.1



/**
 * EmployedAt generated by hbm2java
 */
public class EmployedAt  implements java.io.Serializable {


     private EmployedAtId id;
     private User user;

    public EmployedAt() {
    }

	
    public EmployedAt(EmployedAtId id) {
        this.id = id;
    }
    public EmployedAt(EmployedAtId id, User user) {
       this.id = id;
       this.user = user;
    }
   
    public EmployedAtId getId() {
        return this.id;
    }
    
    public void setId(EmployedAtId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


