package org.nmiljkovic.models;
// Generated Aug 23, 2017 10:48:40 PM by Hibernate Tools 4.3.1



/**
 * EmployedAtId generated by hbm2java
 */
public class EmployedAtId  implements java.io.Serializable {


     private Integer user;
     private Integer airlines;

    public EmployedAtId() {
    }

    public EmployedAtId(Integer user, Integer airlines) {
       this.user = user;
       this.airlines = airlines;
    }
   
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public Integer getAirlines() {
        return this.airlines;
    }
    
    public void setAirlines(Integer airlines) {
        this.airlines = airlines;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployedAtId) ) return false;
		 EmployedAtId castOther = ( EmployedAtId ) other; 
         
		 return ( (this.getUser()==castOther.getUser()) || ( this.getUser()!=null && castOther.getUser()!=null && this.getUser().equals(castOther.getUser()) ) )
 && ( (this.getAirlines()==castOther.getAirlines()) || ( this.getAirlines()!=null && castOther.getAirlines()!=null && this.getAirlines().equals(castOther.getAirlines()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUser() == null ? 0 : this.getUser().hashCode() );
         result = 37 * result + ( getAirlines() == null ? 0 : this.getAirlines().hashCode() );
         return result;
   }   


}


