package org.nmiljkovic.models;
// Generated Aug 25, 2017 1:49:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gate generated by hbm2java
 */
public class Gate  implements java.io.Serializable {


     private Integer id;
     private Airport airport;
     private int terminal;
     private String gate;
     private Set flightsForEndGate = new HashSet(0);
     private Set flightsForStartGate = new HashSet(0);

    public Gate() {
    }

	
    public Gate(Airport airport, int terminal, String gate) {
        this.airport = airport;
        this.terminal = terminal;
        this.gate = gate;
    }
    public Gate(Airport airport, int terminal, String gate, Set flightsForEndGate, Set flightsForStartGate) {
       this.airport = airport;
       this.terminal = terminal;
       this.gate = gate;
       this.flightsForEndGate = flightsForEndGate;
       this.flightsForStartGate = flightsForStartGate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Airport getAirport() {
        return this.airport;
    }
    
    public void setAirport(Airport airport) {
        this.airport = airport;
    }
    public int getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(int terminal) {
        this.terminal = terminal;
    }
    public String getGate() {
        return this.gate;
    }
    
    public void setGate(String gate) {
        this.gate = gate;
    }
    public Set getFlightsForEndGate() {
        return this.flightsForEndGate;
    }
    
    public void setFlightsForEndGate(Set flightsForEndGate) {
        this.flightsForEndGate = flightsForEndGate;
    }
    public Set getFlightsForStartGate() {
        return this.flightsForStartGate;
    }
    
    public void setFlightsForStartGate(Set flightsForStartGate) {
        this.flightsForStartGate = flightsForStartGate;
    }




}


