package org.nmiljkovic.models;
// Generated Aug 20, 2017 9:06:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Manufacturer generated by hbm2java
 */
public class Manufacturer  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set aircrafts = new HashSet(0);
     private Set aircraftTypes = new HashSet(0);

    public Manufacturer() {
    }

	
    public Manufacturer(String name) {
        this.name = name;
    }
    public Manufacturer(String name, Set aircrafts, Set aircraftTypes) {
       this.name = name;
       this.aircrafts = aircrafts;
       this.aircraftTypes = aircraftTypes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAircrafts() {
        return this.aircrafts;
    }
    
    public void setAircrafts(Set aircrafts) {
        this.aircrafts = aircrafts;
    }
    public Set getAircraftTypes() {
        return this.aircraftTypes;
    }
    
    public void setAircraftTypes(Set aircraftTypes) {
        this.aircraftTypes = aircraftTypes;
    }




}


