package org.nmiljkovic.models;
// Generated Aug 27, 2017 8:06:21 PM by Hibernate Tools 4.3.1



/**
 * ReservationRequest generated by hbm2java
 */
public class ReservationRequest  implements java.io.Serializable {


     private Integer id;
     private Aircraft aircraft;
     private Airways airwaysByRequester;
     private Airways airwaysByOwner;
     private int status;

    public ReservationRequest() {
    }

    public ReservationRequest(Aircraft aircraft, Airways airwaysByRequester, Airways airwaysByOwner, int status) {
       this.aircraft = aircraft;
       this.airwaysByRequester = airwaysByRequester;
       this.airwaysByOwner = airwaysByOwner;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aircraft getAircraft() {
        return this.aircraft;
    }
    
    public void setAircraft(Aircraft aircraft) {
        this.aircraft = aircraft;
    }
    public Airways getAirwaysByRequester() {
        return this.airwaysByRequester;
    }
    
    public void setAirwaysByRequester(Airways airwaysByRequester) {
        this.airwaysByRequester = airwaysByRequester;
    }
    public Airways getAirwaysByOwner() {
        return this.airwaysByOwner;
    }
    
    public void setAirwaysByOwner(Airways airwaysByOwner) {
        this.airwaysByOwner = airwaysByOwner;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


