package org.nmiljkovic.models;
// Generated Aug 20, 2017 9:06:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Airways airways;
     private int flag;
     private String firstName;
     private String lastName;
     private Date dateOfBirth;
     private String email;
     private String username;
     private String password;

    public User() {
    }

    public User(Airways airways, int flag, String firstName, String lastName, Date dateOfBirth, String email, String username, String password) {
       this.airways = airways;
       this.flag = flag;
       this.firstName = firstName;
       this.lastName = lastName;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Airways getAirways() {
        return this.airways;
    }
    
    public void setAirways(Airways airways) {
        this.airways = airways;
    }
    public int getFlag() {
        return this.flag;
    }
    
    public void setFlag(int flag) {
        this.flag = flag;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


